unique_ids:
  assets:
    standard-page.html: UF5DIKDBQNEGO7YHVY2PUG5LXQSACEGC
    theme.css: EKFASCVN7GUKN5XJWPE62EFF4CWIBJPK
  forms:
    Form1: VMCZEWG3AOY3LXODQCUE7F7HMYCOMZ4F
  modules: {}
  scripts: {}
  server_modules: {}
